server:
  ssl:
    key-store: /merge/keyStore.p12
    key-store-password: ValeJaco0409!
    key-store-type: pkcs12
    key-password: ValeJaco0409!
    enabled: true
  port: 8443

spring:
  h2:
   console.enabled: true
  sql:
    init.platform: mysql
    init:
      mode: embedded
  datasource:
   url: jdbc:mysql://localhost:3306/cflh
   #   url: jdbc:h2:mem:cflh
   username: cflh
   password: CfLh!2022
   driver-class-name: com.mysql.cj.jdbc.Driver
  jpa :
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type: TRACE

