INSERT INTO USER ( USERNAME , PASSWORD ) values ( 'lala' , 'lala' );
INSERT INTO USER ( USERNAME , PASSWORD ) values ( 'lolo' , 'lolo' );
INSERT INTO USER ( USERNAME , PASSWORD ) values ( 'Valé' , 'Valé' );
INSERT INTO USER ( USERNAME , PASSWORD ) values ( 'Ludo' , 'Ludo' );

INSERT INTO SEANCE ( NAME , MAX_SPOT , START_DATE , DURATION , LOCATION , COACH_ID ) values ( 'WOD PLUS' , 12 , '2021-12-20 18:00:00' , 90 , null , null );
INSERT INTO SEANCE ( NAME , MAX_SPOT , START_DATE , DURATION , LOCATION , COACH_ID ) values ( 'WOD' , 12 , '2021-12-20 19:30:00' , 90 , null , null );
INSERT INTO SEANCE ( NAME , MAX_SPOT , START_DATE , DURATION , LOCATION , COACH_ID ) values ( 'WOD' , 9 , '2021-12-21 18:00:00' , 90 , null , null );
INSERT INTO SEANCE ( NAME , MAX_SPOT , START_DATE , DURATION , LOCATION , COACH_ID ) values ( 'SPECIAL HALTERO' , 250 , '2021-12-21 19:00:00' , 90 , null , null );
INSERT INTO SEANCE ( NAME , MAX_SPOT , START_DATE , DURATION , LOCATION , COACH_ID ) values ( 'QUICK DEATH' , 12 , '2021-12-22 19:00:00' , 90 , null , null );
INSERT INTO SEANCE ( NAME , MAX_SPOT , START_DATE , DURATION , LOCATION , COACH_ID ) values ( 'SPECIAL CARDIO' , 5 , '2021-12-23 20:00:00' , 90 , null , null );

INSERT INTO ROLE values ( null , 'ROLE_MEMBER' );
INSERT INTO ROLE values ( null , 'ROLE_COACH' );
INSERT INTO ROLE values ( null , 'ROLE_OFFICE' );

INSERT INTO USER_ROLES values ( 1 , 1 );

